service: reddit-newsletter

provider:
  name: aws
  stage: prod
  runtime: python3.9
  region: eu-west-1
  timeout: 60
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action: 'logs:*'
        Resource: '*'
      - Effect: 'Allow'
        Action: 'ses:SendEmail'
        Resource: '*'

package:
  patterns:
    - "!node_modules/**"
    - "!serverless_deployment/**"
    - "!assets/**"

functions:
  main:
    handler: src/reddit_weekly.lambda_handler
    events:
      - schedule: cron(0 10 ? * FRI *)
    environment:
      SUBREDDITS: aws,cscareerquestions,devops,Python,programming,tech,technology
      SENDER_MAIL: antoine.delia@gmail.com
      RECIPIENTS_MAILS: antoine.delia@gmail.com
      POST_LIMIT: 10

plugins:
  - serverless-python-requirements
